# Generated by gallery/generate.py; do not edit.
function immersiveengineering_gallery:clear_page_2
# p2-coke-oven-north: coke oven, north-facing normal
place template immersiveengineering:multiblocks/coke_oven 160 100 160 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p2-coke-oven-north",formed_block:"immersiveengineering:coke_oven",template:"immersiveengineering:multiblocks/coke_oven",origin:[I;160,100,160],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p2-coke-oven-east-control: coke oven, east-facing orientation control
place template immersiveengineering:multiblocks/coke_oven 180 100 160 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p2-coke-oven-east-control",formed_block:"immersiveengineering:coke_oven",template:"immersiveengineering:multiblocks/coke_oven",origin:[I;180,100,160],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p2-blast-furnace-north: blast furnace, north-facing normal
place template immersiveengineering:multiblocks/blast_furnace 208 100 160 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p2-blast-furnace-north",formed_block:"immersiveengineering:blast_furnace",template:"immersiveengineering:multiblocks/blast_furnace",origin:[I;208,100,160],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p2-advanced-blast-furnace-north: advanced blast furnace, north-facing normal
place template immersiveengineering:multiblocks/improved_blast_furnace 256 100 160 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p2-advanced-blast-furnace-north",formed_block:"immersiveengineering:advanced_blast_furnace",template:"immersiveengineering:multiblocks/improved_blast_furnace",origin:[I;256,100,160],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p2-alloy-smelter-north: alloy smelter, north-facing normal
place template immersiveengineering:multiblocks/alloy_smelter 304 100 160 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p2-alloy-smelter-north",formed_block:"immersiveengineering:alloy_smelter",template:"immersiveengineering:multiblocks/alloy_smelter",origin:[I;304,100,160],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
function immersiveengineering_gallery:verify_page_2
