# Generated by gallery/generate.py; do not edit.
function immersiveengineering_gallery:clear_page_5
# p5-lightning-rod-north: lightning rod, north-facing normal
place template immersiveengineering:multiblocks/lightning_rod 160 100 544 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-lightning-rod-north",formed_block:"immersiveengineering:lightning_rod",template:"immersiveengineering:multiblocks/lightning_rod",multiblock:"immersiveengineering:multiblocks/lightning_rod",origin:[I;160,100,544],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p5-bucket-wheel-north: bucket wheel, north-facing normal
place template immersiveengineering:multiblocks/bucket_wheel 280 100 544 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-bucket-wheel-north",formed_block:"immersiveengineering:bucket_wheel",template:"immersiveengineering:multiblocks/bucket_wheel",multiblock:"immersiveengineering:multiblocks/bucket_wheel",origin:[I;280,100,544],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p5-bucket-wheel-east-control: bucket wheel, east-facing orientation control
place template immersiveengineering:multiblocks/bucket_wheel 312 100 544 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-bucket-wheel-east-control",formed_block:"immersiveengineering:bucket_wheel",template:"immersiveengineering:multiblocks/bucket_wheel",multiblock:"immersiveengineering:multiblocks/bucket_wheel",origin:[I;312,100,544],formation_origin_offset:[I;0,0,0],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p5-excavator-north: excavator, north-facing normal
place template immersiveengineering:multiblocks/excavator_full 160 100 664 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-excavator-north",formed_block:"immersiveengineering:excavator",template:"immersiveengineering:multiblocks/excavator_full",multiblock:"immersiveengineering:multiblocks/excavator",origin:[I;160,100,664],formation_origin_offset:[I;0,2,2],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p5-excavator-north-mirrored: excavator, north-facing mirrored
place template immersiveengineering:multiblocks/excavator_full 192 100 664 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-excavator-north-mirrored",formed_block:"immersiveengineering:excavator",template:"immersiveengineering:multiblocks/excavator_full",multiblock:"immersiveengineering:multiblocks/excavator",origin:[I;192,100,664],formation_origin_offset:[I;0,2,2],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p5-excavator-east-control: excavator, east-facing orientation control
place template immersiveengineering:multiblocks/excavator_full 224 100 664 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-excavator-east-control",formed_block:"immersiveengineering:excavator",template:"immersiveengineering:multiblocks/excavator_full",multiblock:"immersiveengineering:multiblocks/excavator",origin:[I;224,100,664],formation_origin_offset:[I;0,2,2],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p5-radio-tower-north: radio tower, north-facing normal
place template immersiveengineering:multiblocks/radio_tower 280 100 664 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-radio-tower-north",formed_block:"immersiveengineering:radio_tower",template:"immersiveengineering:multiblocks/radio_tower",multiblock:"immersiveengineering:multiblocks/radio_tower",origin:[I;280,100,664],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p5-radio-tower-north-mirrored: radio tower, north-facing mirrored
place template immersiveengineering:multiblocks/radio_tower 312 100 664 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-radio-tower-north-mirrored",formed_block:"immersiveengineering:radio_tower",template:"immersiveengineering:multiblocks/radio_tower",multiblock:"immersiveengineering:multiblocks/radio_tower",origin:[I;312,100,664],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p5-radio-tower-east-control: radio tower, east-facing orientation control
place template immersiveengineering:multiblocks/radio_tower 344 100 664 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p5-radio-tower-east-control",formed_block:"immersiveengineering:radio_tower",template:"immersiveengineering:multiblocks/radio_tower",multiblock:"immersiveengineering:multiblocks/radio_tower",origin:[I;344,100,664],formation_origin_offset:[I;0,0,0],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
function immersiveengineering_gallery:verify_page_5
