# Generated by gallery/generate.py; do not edit.
function immersiveengineering_gallery:clear_page_3
# p3-crusher-north: crusher, north-facing normal
place template immersiveengineering:multiblocks/crusher 160 100 256 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-crusher-north",formed_block:"immersiveengineering:crusher",template:"immersiveengineering:multiblocks/crusher",multiblock:"immersiveengineering:multiblocks/crusher",origin:[I;160,100,256],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-crusher-north-mirrored: crusher, north-facing mirrored
place template immersiveengineering:multiblocks/crusher 180 100 256 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-crusher-north-mirrored",formed_block:"immersiveengineering:crusher",template:"immersiveengineering:multiblocks/crusher",multiblock:"immersiveengineering:multiblocks/crusher",origin:[I;180,100,256],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-crusher-east-control: crusher, east-facing orientation control
place template immersiveengineering:multiblocks/crusher 200 100 256 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-crusher-east-control",formed_block:"immersiveengineering:crusher",template:"immersiveengineering:multiblocks/crusher",multiblock:"immersiveengineering:multiblocks/crusher",origin:[I;200,100,256],formation_origin_offset:[I;0,0,0],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-fermenter-north: fermenter, north-facing normal
place template immersiveengineering:multiblocks/fermenter 232 100 256 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-fermenter-north",formed_block:"immersiveengineering:fermenter",template:"immersiveengineering:multiblocks/fermenter",multiblock:"immersiveengineering:multiblocks/fermenter",origin:[I;232,100,256],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-fermenter-north-mirrored: fermenter, north-facing mirrored
place template immersiveengineering:multiblocks/fermenter 252 100 256 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-fermenter-north-mirrored",formed_block:"immersiveengineering:fermenter",template:"immersiveengineering:multiblocks/fermenter",multiblock:"immersiveengineering:multiblocks/fermenter",origin:[I;252,100,256],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-diesel-generator-north: diesel generator, north-facing normal
place template immersiveengineering:multiblocks/diesel_generator 304 100 256 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-diesel-generator-north",formed_block:"immersiveengineering:diesel_generator",template:"immersiveengineering:multiblocks/diesel_generator",multiblock:"immersiveengineering:multiblocks/diesel_generator",origin:[I;304,100,256],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-diesel-generator-north-mirrored: diesel generator, north-facing mirrored
place template immersiveengineering:multiblocks/diesel_generator 324 100 256 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-diesel-generator-north-mirrored",formed_block:"immersiveengineering:diesel_generator",template:"immersiveengineering:multiblocks/diesel_generator",multiblock:"immersiveengineering:multiblocks/diesel_generator",origin:[I;324,100,256],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-metal-press-north: metal press, north-facing normal
place template immersiveengineering:multiblocks/metal_press 160 100 288 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-metal-press-north",formed_block:"immersiveengineering:metal_press",template:"immersiveengineering:multiblocks/metal_press",multiblock:"immersiveengineering:multiblocks/metal_press",origin:[I;160,100,288],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-metal-press-north-mirrored: metal press, north-facing mirrored
place template immersiveengineering:multiblocks/metal_press 180 100 288 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-metal-press-north-mirrored",formed_block:"immersiveengineering:metal_press",template:"immersiveengineering:multiblocks/metal_press",multiblock:"immersiveengineering:multiblocks/metal_press",origin:[I;180,100,288],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-assembler-north: assembler, north-facing normal
place template immersiveengineering:multiblocks/assembler 232 100 288 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-assembler-north",formed_block:"immersiveengineering:assembler",template:"immersiveengineering:multiblocks/assembler",multiblock:"immersiveengineering:multiblocks/assembler",origin:[I;232,100,288],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-assembler-east-control: assembler, east-facing orientation control
place template immersiveengineering:multiblocks/assembler 252 100 288 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-assembler-east-control",formed_block:"immersiveengineering:assembler",template:"immersiveengineering:multiblocks/assembler",multiblock:"immersiveengineering:multiblocks/assembler",origin:[I;252,100,288],formation_origin_offset:[I;0,0,0],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-auto-workbench-north: auto workbench, north-facing normal
place template immersiveengineering:multiblocks/auto_workbench 304 100 288 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-auto-workbench-north",formed_block:"immersiveengineering:auto_workbench",template:"immersiveengineering:multiblocks/auto_workbench",multiblock:"immersiveengineering:multiblocks/auto_workbench",origin:[I;304,100,288],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-auto-workbench-north-mirrored: auto workbench, north-facing mirrored
place template immersiveengineering:multiblocks/auto_workbench 324 100 288 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-auto-workbench-north-mirrored",formed_block:"immersiveengineering:auto_workbench",template:"immersiveengineering:multiblocks/auto_workbench",multiblock:"immersiveengineering:multiblocks/auto_workbench",origin:[I;324,100,288],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-bottling-machine-north: bottling machine, north-facing normal
place template immersiveengineering:multiblocks/bottling_machine 160 100 320 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-bottling-machine-north",formed_block:"immersiveengineering:bottling_machine",template:"immersiveengineering:multiblocks/bottling_machine",multiblock:"immersiveengineering:multiblocks/bottling_machine",origin:[I;160,100,320],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-bottling-machine-north-mirrored: bottling machine, north-facing mirrored
place template immersiveengineering:multiblocks/bottling_machine 180 100 320 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-bottling-machine-north-mirrored",formed_block:"immersiveengineering:bottling_machine",template:"immersiveengineering:multiblocks/bottling_machine",multiblock:"immersiveengineering:multiblocks/bottling_machine",origin:[I;180,100,320],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-mixer-north: mixer, north-facing normal
place template immersiveengineering:multiblocks/mixer 232 100 320 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-mixer-north",formed_block:"immersiveengineering:mixer",template:"immersiveengineering:multiblocks/mixer",multiblock:"immersiveengineering:multiblocks/mixer",origin:[I;232,100,320],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-mixer-north-mirrored: mixer, north-facing mirrored
place template immersiveengineering:multiblocks/mixer 252 100 320 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-mixer-north-mirrored",formed_block:"immersiveengineering:mixer",template:"immersiveengineering:multiblocks/mixer",multiblock:"immersiveengineering:multiblocks/mixer",origin:[I;252,100,320],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-refinery-north: refinery, north-facing normal
place template immersiveengineering:multiblocks/refinery 304 100 320 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-refinery-north",formed_block:"immersiveengineering:refinery",template:"immersiveengineering:multiblocks/refinery",multiblock:"immersiveengineering:multiblocks/refinery",origin:[I;304,100,320],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-refinery-north-mirrored: refinery, north-facing mirrored
place template immersiveengineering:multiblocks/refinery 324 100 320 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-refinery-north-mirrored",formed_block:"immersiveengineering:refinery",template:"immersiveengineering:multiblocks/refinery",multiblock:"immersiveengineering:multiblocks/refinery",origin:[I;324,100,320],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-squeezer-north: squeezer, north-facing normal
place template immersiveengineering:multiblocks/squeezer 160 100 352 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-squeezer-north",formed_block:"immersiveengineering:squeezer",template:"immersiveengineering:multiblocks/squeezer",multiblock:"immersiveengineering:multiblocks/squeezer",origin:[I;160,100,352],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-squeezer-north-mirrored: squeezer, north-facing mirrored
place template immersiveengineering:multiblocks/squeezer 180 100 352 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-squeezer-north-mirrored",formed_block:"immersiveengineering:squeezer",template:"immersiveengineering:multiblocks/squeezer",multiblock:"immersiveengineering:multiblocks/squeezer",origin:[I;180,100,352],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-sawmill-north: sawmill, north-facing normal
place template immersiveengineering:multiblocks/sawmill 232 100 352 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-sawmill-north",formed_block:"immersiveengineering:sawmill",template:"immersiveengineering:multiblocks/sawmill",multiblock:"immersiveengineering:multiblocks/sawmill",origin:[I;232,100,352],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-sawmill-north-mirrored: sawmill, north-facing mirrored
place template immersiveengineering:multiblocks/sawmill 252 100 352 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-sawmill-north-mirrored",formed_block:"immersiveengineering:sawmill",template:"immersiveengineering:multiblocks/sawmill",multiblock:"immersiveengineering:multiblocks/sawmill",origin:[I;252,100,352],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-arc-furnace-north: arc furnace, north-facing normal
place template immersiveengineering:multiblocks/arcfurnace 304 100 352 none none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-arc-furnace-north",formed_block:"immersiveengineering:arc_furnace",template:"immersiveengineering:multiblocks/arcfurnace",multiblock:"immersiveengineering:multiblocks/arcfurnace",origin:[I;304,100,352],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:form
# p3-arc-furnace-north-mirrored: arc furnace, north-facing mirrored
place template immersiveengineering:multiblocks/arcfurnace 324 100 352 none front_back 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-arc-furnace-north-mirrored",formed_block:"immersiveengineering:arc_furnace",template:"immersiveengineering:multiblocks/arcfurnace",multiblock:"immersiveengineering:multiblocks/arcfurnace",origin:[I;324,100,352],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:form
# p3-arc-furnace-east-control: arc furnace, east-facing orientation control
place template immersiveengineering:multiblocks/arcfurnace 344 100 352 clockwise_90 none 1.0 0
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p3-arc-furnace-east-control",formed_block:"immersiveengineering:arc_furnace",template:"immersiveengineering:multiblocks/arcfurnace",multiblock:"immersiveengineering:multiblocks/arcfurnace",origin:[I;344,100,352],formation_origin_offset:[I;0,0,0],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:form
fill 152 99 248 352 99 360 minecraft:smooth_stone
function immersiveengineering_gallery:verify_page_3
