# Generated by gallery/generate.py; do not edit.
fill 154 99 410 166 109 422 minecraft:air
fill 217 99 409 231 106 423 minecraft:air
fill 154 99 442 166 107 454 minecraft:air
fill 174 99 442 186 107 454 minecraft:air
fill 218 99 442 230 107 454 minecraft:air
fill 238 99 442 250 107 454 minecraft:air
fill 258 99 442 270 107 454 minecraft:air
