# Generated by gallery/generate.py; do not edit.
tellraw @a {"text":"Immersive Engineering gallery loaded; install immersiveengineering_gallery_helper and run /function immersiveengineering_gallery:build","color":"yellow"}
