# Generated by gallery/generate.py; do not edit.
# p2-coke-oven-north: coke oven, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p2-coke-oven-north",formed_block:"immersiveengineering:coke_oven",template:"immersiveengineering:multiblocks/coke_oven",multiblock:"immersiveengineering:multiblocks/coke_oven",origin:[I;160,100,160],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p2-coke-oven-east-control: coke oven, east-facing orientation control
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p2-coke-oven-east-control",formed_block:"immersiveengineering:coke_oven",template:"immersiveengineering:multiblocks/coke_oven",multiblock:"immersiveengineering:multiblocks/coke_oven",origin:[I;180,100,160],formation_origin_offset:[I;0,0,0],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p2-blast-furnace-north: blast furnace, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p2-blast-furnace-north",formed_block:"immersiveengineering:blast_furnace",template:"immersiveengineering:multiblocks/blast_furnace",multiblock:"immersiveengineering:multiblocks/blast_furnace",origin:[I;208,100,160],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p2-advanced-blast-furnace-north: advanced blast furnace, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p2-advanced-blast-furnace-north",formed_block:"immersiveengineering:advanced_blast_furnace",template:"immersiveengineering:multiblocks/improved_blast_furnace",multiblock:"immersiveengineering:multiblocks/improved_blast_furnace",origin:[I;256,100,160],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p2-alloy-smelter-north: alloy smelter, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:2,case_id:"p2-alloy-smelter-north",formed_block:"immersiveengineering:alloy_smelter",template:"immersiveengineering:multiblocks/alloy_smelter",multiblock:"immersiveengineering:multiblocks/alloy_smelter",origin:[I;304,100,160],formation_origin_offset:[I;0,0,0],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
tellraw @a {"text":"Immersive Engineering page 2 checked","color":"yellow"}
