# Generated by gallery/generate.py; do not edit.
# p3-crusher-north: crusher, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-crusher-north",formed_block:"immersiveengineering:crusher",template:"immersiveengineering:multiblocks/crusher",origin:[I;160,100,256],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-crusher-north-mirrored: crusher, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-crusher-north-mirrored",formed_block:"immersiveengineering:crusher",template:"immersiveengineering:multiblocks/crusher",origin:[I;180,100,256],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-crusher-east-control: crusher, east-facing orientation control
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-crusher-east-control",formed_block:"immersiveengineering:crusher",template:"immersiveengineering:multiblocks/crusher",origin:[I;200,100,256],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-fermenter-north: fermenter, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-fermenter-north",formed_block:"immersiveengineering:fermenter",template:"immersiveengineering:multiblocks/fermenter",origin:[I;232,100,256],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-fermenter-north-mirrored: fermenter, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-fermenter-north-mirrored",formed_block:"immersiveengineering:fermenter",template:"immersiveengineering:multiblocks/fermenter",origin:[I;252,100,256],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-diesel-generator-north: diesel generator, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-diesel-generator-north",formed_block:"immersiveengineering:diesel_generator",template:"immersiveengineering:multiblocks/diesel_generator",origin:[I;304,100,256],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-diesel-generator-north-mirrored: diesel generator, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-diesel-generator-north-mirrored",formed_block:"immersiveengineering:diesel_generator",template:"immersiveengineering:multiblocks/diesel_generator",origin:[I;324,100,256],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-metal-press-north: metal press, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-metal-press-north",formed_block:"immersiveengineering:metal_press",template:"immersiveengineering:multiblocks/metal_press",origin:[I;160,100,288],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-metal-press-north-mirrored: metal press, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-metal-press-north-mirrored",formed_block:"immersiveengineering:metal_press",template:"immersiveengineering:multiblocks/metal_press",origin:[I;180,100,288],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-assembler-north: assembler, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-assembler-north",formed_block:"immersiveengineering:assembler",template:"immersiveengineering:multiblocks/assembler",origin:[I;232,100,288],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-assembler-east-control: assembler, east-facing orientation control
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-assembler-east-control",formed_block:"immersiveengineering:assembler",template:"immersiveengineering:multiblocks/assembler",origin:[I;252,100,288],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-auto-workbench-north: auto workbench, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-auto-workbench-north",formed_block:"immersiveengineering:auto_workbench",template:"immersiveengineering:multiblocks/auto_workbench",origin:[I;304,100,288],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-auto-workbench-north-mirrored: auto workbench, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-auto-workbench-north-mirrored",formed_block:"immersiveengineering:auto_workbench",template:"immersiveengineering:multiblocks/auto_workbench",origin:[I;324,100,288],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-bottling-machine-north: bottling machine, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-bottling-machine-north",formed_block:"immersiveengineering:bottling_machine",template:"immersiveengineering:multiblocks/bottling_machine",origin:[I;160,100,320],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-bottling-machine-north-mirrored: bottling machine, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-bottling-machine-north-mirrored",formed_block:"immersiveengineering:bottling_machine",template:"immersiveengineering:multiblocks/bottling_machine",origin:[I;180,100,320],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-mixer-north: mixer, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-mixer-north",formed_block:"immersiveengineering:mixer",template:"immersiveengineering:multiblocks/mixer",origin:[I;232,100,320],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-mixer-north-mirrored: mixer, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-mixer-north-mirrored",formed_block:"immersiveengineering:mixer",template:"immersiveengineering:multiblocks/mixer",origin:[I;252,100,320],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-refinery-north: refinery, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-refinery-north",formed_block:"immersiveengineering:refinery",template:"immersiveengineering:multiblocks/refinery",origin:[I;304,100,320],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-refinery-north-mirrored: refinery, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-refinery-north-mirrored",formed_block:"immersiveengineering:refinery",template:"immersiveengineering:multiblocks/refinery",origin:[I;324,100,320],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-squeezer-north: squeezer, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-squeezer-north",formed_block:"immersiveengineering:squeezer",template:"immersiveengineering:multiblocks/squeezer",origin:[I;160,100,352],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-squeezer-north-mirrored: squeezer, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-squeezer-north-mirrored",formed_block:"immersiveengineering:squeezer",template:"immersiveengineering:multiblocks/squeezer",origin:[I;180,100,352],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-sawmill-north: sawmill, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-sawmill-north",formed_block:"immersiveengineering:sawmill",template:"immersiveengineering:multiblocks/sawmill",origin:[I;232,100,352],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-sawmill-north-mirrored: sawmill, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-sawmill-north-mirrored",formed_block:"immersiveengineering:sawmill",template:"immersiveengineering:multiblocks/sawmill",origin:[I;252,100,352],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-arc-furnace-north: arc furnace, north-facing normal
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-arc-furnace-north",formed_block:"immersiveengineering:arc_furnace",template:"immersiveengineering:multiblocks/arcfurnace",origin:[I;304,100,352],facing:"north",mirrored:0b}
function immersiveengineering_gallery_helper:verify
# p3-arc-furnace-north-mirrored: arc furnace, north-facing mirrored
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-arc-furnace-north-mirrored",formed_block:"immersiveengineering:arc_furnace",template:"immersiveengineering:multiblocks/arcfurnace",origin:[I;324,100,352],facing:"north",mirrored:1b}
function immersiveengineering_gallery_helper:verify
# p3-arc-furnace-east-control: arc furnace, east-facing orientation control
data modify storage immersiveengineering_gallery:formation request set value {schema:1,case_id:"p3-arc-furnace-east-control",formed_block:"immersiveengineering:arc_furnace",template:"immersiveengineering:multiblocks/arcfurnace",origin:[I;344,100,352],facing:"east",mirrored:0b}
function immersiveengineering_gallery_helper:verify
tellraw @a {"text":"Immersive Engineering page 3 checked","color":"yellow"}
