#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the deterministic multiblock review gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import cases
from ie_gallery.model import GalleryCase, GalleryPage


ROOT = Path(__file__).resolve().parent


def text_bytes(value: str) -> bytes:
    return (value.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return text_bytes(json.dumps(value, indent=2, sort_keys=True))


def placements_tsv() -> bytes:
    lines = [
        "case_id\tpage\tlabel\tx\ty\tz\tformed_block\ttemplate\t"
        "facing\tmirrored\texpected"
    ]
    lines.extend(
        "\t".join(
            (
                case.case_id,
                str(case.page),
                case.label,
                str(case.x),
                str(case.y),
                str(case.z),
                case.structure.block_id,
                case.structure.template_id,
                case.facing,
                str(case.mirrored).lower(),
                case.expected,
            )
        )
        for case in cases.PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def request_value(case: GalleryCase) -> str:
    mirrored = "1b" if case.mirrored else "0b"
    return (
        "{schema:1,"
        f'case_id:"{case.case_id}",'
        f'formed_block:"{case.structure.block_id}",'
        f'template:"{case.structure.template_id}",'
        f"origin:[I;{case.x},{case.y},{case.z}],"
        f'facing:"{case.facing}",mirrored:{mirrored}'
        "}"
    )


def set_request(case: GalleryCase) -> str:
    return (
        f"data modify storage {cases.STORAGE} request set value "
        f"{request_value(case)}"
    )


def clear_page_function(page: GalleryPage) -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    for case in page.cases:
        minimum_x, minimum_y, minimum_z, maximum_x, maximum_y, maximum_z = (
            case.clear_bounds()
        )
        lines.append(
            f"fill {minimum_x} {minimum_y} {minimum_z} "
            f"{maximum_x} {maximum_y} {maximum_z} minecraft:air"
        )
    return text_bytes("\n".join(lines))


def build_page_function(page: GalleryPage) -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {cases.NAMESPACE}:clear_page_{page.number}",
    ]
    for case in page.cases:
        lines.extend(
            (
                f"# {case.case_id}: {case.label}",
                f"place template {case.structure.template_id} "
                f"{case.x} {case.y} {case.z} {case.rotation} "
                f"{case.mirror} 1.0 0",
                set_request(case),
                f"function {cases.HELPER_NAMESPACE}:form",
            )
        )
    lines.append(f"function {cases.NAMESPACE}:verify_page_{page.number}")
    return text_bytes("\n".join(lines))


def verify_page_function(page: GalleryPage) -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    for case in page.cases:
        lines.extend(
            (
                f"# {case.case_id}: {case.label}",
                set_request(case),
                f"function {cases.HELPER_NAMESPACE}:verify",
            )
        )
    lines.append(
        "tellraw @a "
        f'{{"text":"Immersive Engineering page {page.number} checked",'
        '"color":"yellow"}'
    )
    return text_bytes("\n".join(lines))


def clear_function() -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    lines.extend(
        f"function {cases.NAMESPACE}:clear_page_{page.number}"
        for page in cases.PAGES
    )
    return text_bytes("\n".join(lines))


def build_function() -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    lines.extend(
        f"function {cases.NAMESPACE}:build_page_{page.number}"
        for page in cases.PAGES
    )
    lines.append(
        "tellraw @a "
        '{"text":"Immersive Engineering formed gallery built",'
        '"color":"yellow"}'
    )
    return text_bytes("\n".join(lines))


def verify_function() -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    lines.extend(
        f"function {cases.NAMESPACE}:verify_page_{page.number}"
        for page in cases.PAGES
    )
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{cases.NAMESPACE}/function")
    files = {
        Path("placements.tsv"): placements_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": (
                        "ATM 1.2.0 Immersive Engineering formed multiblock gallery"
                    ),
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{cases.NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            "tellraw @a {\"text\":\"Immersive Engineering gallery loaded; "
            f"install {cases.HELPER_NAMESPACE} and run /function "
            f"{cases.NAMESPACE}:build\",\"color\":\"yellow\"}}"
        ),
        function_root / "clear.mcfunction": clear_function(),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"function {cases.NAMESPACE}:clear\n"
            f"data remove storage {cases.STORAGE} request"
        ),
    }
    for page in cases.PAGES:
        files[function_root / f"clear_page_{page.number}.mcfunction"] = (
            clear_page_function(page)
        )
        files[function_root / f"build_page_{page.number}.mcfunction"] = (
            build_page_function(page)
        )
        files[function_root / f"verify_page_{page.number}.mcfunction"] = (
            verify_page_function(page)
        )
    return files


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{hashlib.sha256(payload).hexdigest()}  {path.as_posix()}\n"
        for path, payload in sorted(files.items(), key=lambda row: row[0].as_posix())
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def stale_generated_functions(expected: set[Path]) -> tuple[Path, ...]:
    function_root = ROOT / f"datapack/data/{cases.NAMESPACE}/function"
    if not function_root.is_dir():
        return ()
    return tuple(
        path
        for path in sorted(function_root.glob("*.mcfunction"))
        if path.relative_to(ROOT) not in expected
    )


def write_or_check(check: bool) -> int:
    generated = generated_files()
    expected = set(generated)
    failures = []
    for relative, payload in generated.items():
        destination = ROOT / relative
        if check:
            if not destination.is_file() or destination.read_bytes() != payload:
                failures.append(relative.as_posix())
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(payload)

    stale = stale_generated_functions(expected)
    if check:
        failures.extend(path.relative_to(ROOT).as_posix() for path in stale)
    else:
        for path in stale:
            path.unlink()

    if failures:
        print(f"generated gallery differs: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
